# dataset name
dataset: 'cifar10'
# create imbalanced data
# select imb_type and imb_factor
imb_type: 'exp'
imb_factor: 0.01
rand_number: 0
workers: 4
# model backbone
backbone: 'resnet32'
# model classifier
classifier: 'dot_product_classifier'
# Training related parameters
gpu: 0
start_epoch: 0
epochs: 200
batch_size: 128
optimizer: 'sgd'
learning_rate: 0.1
momentum: 0.9
weight_decay: 2e-4
# Remix hyper parameter
k_majority: 3
tau: 0.5
# MAMix hyper parameter
mamix_ratio: -0.25
# logging related
print_freq: 10
root_log: 'log_cifar10'
root_model: 'checkpoint_cifar10'
layers: 'layer0'
p: 0.4
lam: 1.
head_threshold: 3
dim: 1